### ISSUE TITLE
Add package manifest apis

### ISSUE THREAD

**Issue by horis233** [operator-framework/api#195]
Do we have a plan to add package manifest api into this repo?

Currently, it is in the OLM repo.
https://github.com/operator-framework/operator-lifecycle-manager/tree/master/pkg/package-server/apis/operators

**Comment by camilamacedo86** [comment]
Hi @horis233, 

What do you mean with `Do we have a plan to add package manifest api into this repo?`

The API is able to load the package manifest format and then, you can use all validators with as well, e.g: 

You can for example, load the dir where you have the package manifest by converting it to bundle format:

```go
// Load the bundle
			bundle, err := apimanifests.GetBundleFromDir(path)
			if err != nil {
				o.Errors = append(o.Errors,
					BundleDir{Path: strings.ReplaceAll(path, o.CurrentPath, ""), Error: fmt.Sprintf("Unable to load the bundle: %s", err.Error())})
				return nil
			}
```

Then, you can call the validators: 

```go
validators := apivalidation.DefaultBundleValidators
	validators = validators.WithValidators(apivalidation.AlphaDeprecatedAPIsValidator)

	objs := bundle.ObjectsToValidate()

	results := validators.Validate(objs...)
	nonEmptyResults := []errors.ManifestResult{}

	for _, result := range results {
		if result.HasError() || result.HasWarn() {
			nonEmptyResults = append(nonEmptyResults, result)
		}
	}


```

However, besides this format still being supported is recommended to Operator Authors move forward and adopted the bundle format. You can easily do that and migrate your package to bundle format by using the commands:
- `$ operator-sdk pkgman-to-bundle <package_manifests_dir> \ 
    [--output-dir <directory>] \ 
    --image-tag-base <image_name_base> ` (https://docs.openshift.com/container-platform/4.8/operators/operator_sdk/osdk-pkgman-to-bundle.html)
- Or with OPM and its alpha commands. 

 In this way, could you please let us know what is where motivation? What you are looking for to use the operator-framework/API and are unable to do with the package manifest format?

**Comment by camilamacedo86** [comment]
Hi @horis233,

It shows open for a while without interaction.
Could we close this one? It shows stored out or outdated. 
Have we anything else that we should get done here?

**Comment by horis233** [comment]
Sure, Thanks for your help
