### ISSUE TITLE
Remove go-get usage from Makefile in preparation of Go 1.18

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/api#220]
https://github.com/operator-framework/api/pull/213 updated the way that tooling dependencies were pulled in after the root vendor directory had been removed, and the new mechanism relies on `go get ...` functionality which will break in Go 1.18.

See the [Go 1.18 release notes](https://tip.golang.org/doc/go1.18) for more information.

**Comment by camilamacedo86** [comment]
c/c @ryantking

**Comment by ryantking** [comment]
This is handled in kubebuilder by https://github.com/kubernetes-sigs/kubebuilder/pull/2486, once we can release it, we will update the framework components with the changes.
