### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by magescher** [operator-framework/api#40]
I was unable to find a license file associated with the code base. Is this intentional? If not, when/how will this be licensed?

**Comment by dvattaka** [comment]
Hi, Is the operator-framework/api/ is licensed under [Apache License 2.0](https://github.com/operator-framework/api/blob/149a621385f724bac40499ff69f7feb98396151c/LICENSES/Apache-2.0.txt)? If that's the case, could you please add the LICENSE file?

**Comment by benluddy** [comment]
Yes! Thank you for filing an issue. The license can now be found at https://github.com/operator-framework/api/blob/master/LICENSE.
