### ISSUE TITLE
feature request - add log target to GetManifestsDir function

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/api#9]
This is a feature request to add a way to capture logs to the manifests.GetManifestsDir() function.
This would allow callers to capture the logrus output to process as they wish and independent of
the logger being used within the api.  

Something perhaps like:

manifests.GetManifestsDir(dir string, logOutput io.Writer) (...)

**Comment by estroz** [comment]
Should be resolved once https://github.com/operator-framework/operator-registry/pull/131 is merged and deps are updated here.

**Comment by camilamacedo86** [comment]
I think we can close this one as outdated. 
@exdx @dinhxuanvu I have no permission in this repo. Could you please help us out?

**Comment by exdx** [comment]
Closing as stale as the related PR has been closed. Please feel free to reopen if this is still a priority issue.
